server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: HOTEL-SERVICE
  config:
    import: optional:configserver:http://localhost:8085


#  http://localhost:8085 => this is the config server port where we have linked our GitHub configurations and from there we are fetching out configs.


#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka